// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCccn2uGOvLpc3cR9dLwmIzMT2mKJTy1AM',
    appId: '1:912729450201:web:9ac0d515d109091b2900c8',
    messagingSenderId: '912729450201',
    projectId: 'wordel-307c4',
    authDomain: 'wordel-307c4.firebaseapp.com',
    storageBucket: 'wordel-307c4.appspot.com',
    measurementId: 'G-LDQ0MM0MZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCNMwTInO1qfOuoWmb0Qm94fHXCwSeAok',
    appId: '1:912729450201:android:bb895597a38c9bfb2900c8',
    messagingSenderId: '912729450201',
    projectId: 'wordel-307c4',
    storageBucket: 'wordel-307c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkK4tsRTep-DeN8BR34AZwtS6tgCYg7l8',
    appId: '1:912729450201:ios:bf47bd443be9e03b2900c8',
    messagingSenderId: '912729450201',
    projectId: 'wordel-307c4',
    storageBucket: 'wordel-307c4.appspot.com',
    iosBundleId: 'com.coriumdata.wordel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkK4tsRTep-DeN8BR34AZwtS6tgCYg7l8',
    appId: '1:912729450201:ios:51915b56341d10022900c8',
    messagingSenderId: '912729450201',
    projectId: 'wordel-307c4',
    storageBucket: 'wordel-307c4.appspot.com',
    iosBundleId: 'com.example.wordel.RunnerTests',
  );
}
